name: Snowstorm CI

on:
  push:
    branches:
      - features/ako/update_branch_fix_RSS_vulnerability_issue
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  Snowstorm-build:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests
        run: mvn --batch-mode --no-transfer-progress clean test -Ddependency-check.skip=true
